### ISSUE TITLE
MOCKUP

### ISSUE THREAD

**Issue by sophalS** [PNC-WEP-ONE-WEEK-PROJECT/PHP-DB-G16#6]

**Comment by Somnak-Kalan** [comment]
Dear Teacher This our Mock up
![account](https://user-images.githubusercontent.com/91930316/158319710-f005769b-6ee5-4169-a21e-5f0a5cbaad58.jpg)
![add form](https://user-images.githubusercontent.com/91930316/158319714-d793cb13-5f7f-41b0-bd81-a8789a3c77b2.jpg)
![home](https://user-images.githubusercontent.com/91930316/158319716-c43ac491-a7f2-4e2b-97d8-d5afed002265.jpg)

**Comment by ronanpnc** [comment]
You should have more consistency between views

YOu should not put too many feature than you will not code  (if we see it, it should work)

**Comment by Somnak-Kalan** [comment]
Home Page
![home](https://user-images.githubusercontent.com/91930316/158491650-a17f4ad0-fcc7-463b-9980-08bfa21dddaf.jpg)

**Comment by Somnak-Kalan** [comment]
Account
![home1](https://user-images.githubusercontent.com/91930316/158491696-e5ec292c-2228-4707-80de-7ddbd7532b22.jpg)

**Comment by Somnak-Kalan** [comment]
Form add post
![Screenshot 2022-03-16 070521](https://user-images.githubusercontent.com/91930316/158491856-441b37a3-e72c-4f25-bff9-21947d56d9e7.jpg)
